runcharts:
  - title: Search engine response time
    position: [[0, 0], [80, 8]]
    rate-ms: 500
    legend:
        enabled: true
        details: false
    scale: 2
    items:
      - label: GOOGLE
        color: 178
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.google.com
      - label: SAMSUNG
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.samsung.com/
      - label: BING
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.bing.com
      - label: NAVER
        color: 10
        sample: curl -o /dev/null -s -w '%{time_total}'  https://www.naver.com
sparklines:
  - title: CPU usage
    position: [[0, 20], [40, 12]]
    rate-ms: 200
    scale: 0
    sample: ps -A -o %cpu | awk '{s+=$1} END {print s}'
  - title: Free memory pages
    position: [[40, 20], [40, 12]]
    rate-ms: 200
    scale: 0
    sample: free | grep Mem | awk '{print $4/$2*100}'
textboxes:
  - title: Local weather
    position: [[0, 8], [27, 13]]
    rate-ms: 10000
    color: 178
    sample: curl wttr.in?0ATQF
    border: false
  - title: Docker containers stats
    position: [[26, 8], [55, 13]]
    rate-ms: 500
    sample: docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.PIDs}}"
asciiboxes:
  - title: UTC time
    position: [[0, 32], [80, 8]]
    rate-ms: 500
    color: 43
    sample: env TZ=UTC date +%r
    border: false
    font: 3d
